# Generated by Django 4.1.3 on 2022-11-30 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='rented',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='barrow',
            name='borrowDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 30, 20, 32, 29, 707861)),
        ),
        migrations.AlterField(
            model_name='books',
            name='archiveDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 30, 20, 32, 29, 706904)),
        ),
        migrations.AlterField(
            model_name='user',
            name='joinDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 30, 20, 32, 29, 704870)),
        ),
    ]
